name = "BeliefPropagation"
uuid = "1f252afb-17b4-4706-9392-c44a09a78db1"
authors = ["Victor Granados <victorgranadosp@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
