name = "DisorderedSystems"
uuid = "2ed5c293-c1bd-4907-8057-d69a734e525d"
authors = ["Victor Granados <victorgranadosp@gmail.com>"]
version = "0.1.0"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
